### ISSUE TITLE
System.ObjectDisposedException in version 2.1.4 in iOS

### ISSUE THREAD

**Issue by geertgeerits** [afriscic/BarcodeScanning.Native.Maui#128]
Hi,

Version 2.1.4 - iOS
The app hangs when going from the mainpage to the scanpage.
Not the first time but after a few times switching between the mainpage and the scanpage
and the error is:

System.ObjectDisposedException:
Cannot access a disposed object.
Object name: AVFoundation.AVCaptureDevice

This was not a problem in version 2.1.3

Tested on an iPad (8th generation) iOS 18.2.  Works fine on Android.

Best regards.

**Comment by UkeHa** [comment]
Can confirm. Run into this issue with latest iOS, .net9 and latest library version. Sometimes crashes on the initial open of the barcode page which seems like a problem with apple vision. Sometimes i can scan 20 times in quick succession before it crashes, but then it does.

Adding a 100ms delay on CameraView_OnDetectionFinished doesn't help with the issue. @afriscic do you need any more info? I could send you crash reports from my current testflight version.

**Comment by dzebas** [comment]
Same here, this is our call stack if helps:

```
<CallStack>
<Exception>ObjectDisposed_Generic ObjectDisposed_ObjectName_Name, AVFoundation.AVCaptureDevice</Exception>
<StackLoc>
<Method>ThrowHelper.ThrowObjectDisposedException</Method>
<Module>Microsoft.iOS.dll</Module>
<SourceFile/>
<SourceLine>0</SourceLine>
<NativeOffset>44</NativeOffset>
</StackLoc>
<StackLoc>
<Method>NativeObjectExtensions.GetNonNullHandle</Method>
<Module>Microsoft.iOS.dll</Module>
<SourceFile/>
<SourceLine>0</SourceLine>
<NativeOffset>CB</NativeOffset>
</StackLoc>
<StackLoc>
<Method>AVCaptureDeviceInput..ctor</Method>
<Module>Microsoft.iOS.dll</Module>
<SourceFile/>
<SourceLine>0</SourceLine>
<NativeOffset>53</NativeOffset>
</StackLoc>
<StackLoc>
<Method><>c__DisplayClass24_0.<UpdateCamera>b__0</Method>
<Module>BarcodeScanning.Native.Maui.dll</Module>
<SourceFile/>
<SourceLine>0</SourceLine>
<NativeOffset>113</NativeOffset>
</StackLoc>
<StackLoc>
<Method>DispatchQueue.static_dispatcher_to_managed</Method>
<Module>Microsoft.iOS.dll</Module>
<SourceFile/>
<SourceLine>0</SourceLine>
<NativeOffset>9F</NativeOffset>
</StackLoc>
<StackLoc>
<Method/>
<SourceFile/>
<SourceLine>0</SourceLine>
<NativeOffset>4F</NativeOffset>
</StackLoc>
</CallStack>
```

**Comment by UkeHa** [comment]
going back to 2.1.3 seems to fix it in my latest testflight.

**Comment by afriscic** [comment]
Hopefully this should be fixed in 2.1.5

**Comment by geertgeerits** [comment]
Hi,
Thanks for the update but unfortunately the problem is not solved. Same error message.

**Comment by UkeHa** [comment]
@geertgeerits, did you revert to 2.1.3?

**Comment by geertgeerits** [comment]
Yes. 2.1.3 is working.

**Comment by afriscic** [comment]
Thanks for info.
I'll probably revert to 2.1.3 for CameraManager on iOS and than try to fix #123 with minimal modifications.

**Comment by afriscic** [comment]
Oh nevermind, I think i see where the problem is.
Thanks @dzebas for the call stack.

Could you please try [#123-fix](https://github.com/afriscic/BarcodeScanning.Native.Maui/tree/%23128-fix) branch? SO that i don't publish blind again because I can't replicate this issue on my device.

**Comment by geertgeerits** [comment]
Hi,
Thanks for the latest release 2.1.6.
No more problems here.

**Comment by UkeHa** [comment]
dito - seems to work here!
